<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <RootNamespace>Mailgun.Extensions.DependencyInjection</RootNamespace>
    <AssemblyName>Mailgun.Extensions.DependencyInjection</AssemblyName>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>mailgun-dotnet.Extensions.DependencyInjection</PackageId>
    <Description>Microsoft.Extensions.DependencyInjection helpers for the mailgun-dotnet SDK.</Description>
    <Authors>Andreas Lohr</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Copyright>Copyright (c) 2026 Andreas Lohr. All rights reserved.</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>mailgun;sdk;email;di;dependencyinjection</PackageTags>
    <Version>0.6.3</Version>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/AndreasLohr/mailgun-dotnet</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mailgun\Mailgun.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

</Project>
